apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.4.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            tailscale.com/tags: "tag:grafana,tag:k8s"
          ingressClassName: tailscale
          hosts:
            - grafana
          tls:
            - hosts:
                - grafana
                - grafana.takaya-map.ts.net


  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
