apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.2.2
    helm:
      valuesObject:
        cluster:
          name: nippon-koku
        clusterMetrics:
          enabled: true
        alloy-metrics:
          enabled: true
        alloy-logs:
          enabled: true
        destinations:
          - name: local-collector
            type: otlp
            url: http://k8s-monitoring-collector:4317/
            metrics: { enabled: true }
            logs:    { enabled: true }
            traces:  { enabled: true }
  destination:
    server: "https://kubernetes.default.svc"
    namespace: k8s-monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
