apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.4
    helm:
      valuesObject:
        cluster:
          name: nippon-koku
        clusterMetrics:
          enabled: true
        alloy-metrics:
          enabled: true
        alloy-logs:
          enabled: true
        destinations: []
          # - name: otlpGateway
          #   type: otlp
          #   url: https://otlp.example.com:4317/v1/traces
          #   auth:
          #     type: basic
          #     username: "my-username"
          #     password: "my-password"
          #   metrics: { enabled: true }
          #   logs:    { enabled: true }
          #   traces:  { enabled: true }
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
