apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: kubetail
    repoURL: https://kubetail-org.github.io/helm-charts
    targetRevision: 0.13.2
    helm:
      releaseName: kubetail
      valuesObject:
        kubetail:
          dashboard:
            ingress:
              enabled: true
              annotations:
                tailscale.com/tags: "tag:kubetail,tag:k8s"
              className: tailscale
              rules:
                - host: kubetail
                  http:
                    paths:
                      - backend:
                          service:
                            name: kubetail-dashboard
                            port:
                              name: http
                        path: /
                        pathType: ImplementationSpecific
              tls:
                - hosts:
                    - kubetail
                    - kubetail.takaya-map.ts.net
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubetail-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
