apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w3-kubetail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: kubetail
    repoURL: https://kubetail-org.github.io/helm-charts
    targetRevision: 0.9.6
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubetail-system
  syncPolicy: {}
