apiVersion: v1
kind: Namespace
metadata:
  name: kubetail-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: appproj-nippon-koku
  source:
    chart: kubetail
    repoURL: https://kubetail-org.github.io/helm-charts
    targetRevision: 0.9.6
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubetail-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetail-tailscale
  namespace: kubetail-system
  annotations:
    tailscale.com/tags: "tag:kubetail,tag:k8s"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - kubetail
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubetail-dashboard
                port:
                  number: 8080
