apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w3-lgtm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.0
    # helm:
    #   valuesObject: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
