apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w3-lgtm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.0
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/tags: "tag:grafana,tag:k8s"
            hosts:
              - grafana
            tls:
              - hosts:
                  - grafana
                  - grafana.takaya-map.ts.net
        loki:
          gateway:
            enabled: false
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/tags: "tag:loki,tag:k8s"
            hosts:
              - loki
            tls:
              - hosts:
                  - loki
                  - loki.takaya-map.ts.net
        mimir:
          gateway:
            enabled: false
          ingress:
            enabled: true
            ingressClassName: tailscale
            annotations:
              tailscale.com/tags: "tag:mimir,tag:k8s"
            hosts:
              - mimir
            tls:
              - hosts:
                  - mimir
                  - mimir.takaya-map.ts.net
        tempo:
          tempoQuery:
            ingress:
              enabled: true
              ingressClassName: tailscale
              annotations:
                tailscale.com/tags: "tag:tempo,tag:k8s"
              hosts:
                - tempo
              tls:
                - hosts:
                    - tempo
                    - tempo.takaya-map.ts.net
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
