apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-aws-secret
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCKQuHmxvQcU2bp1Royh8Az/7y0b+hXQR8tQ4h7gY3o/boSrowF+CyBr8D8UTyyIebAE/myG1wP7xgCYTBUgBfLW1Q6q5XYBB+P43r6cOHAPtOtYr4fCEmJIkqp8d+EIfno5PtcO7ZwXENXMA1k1egv9iSAk1rHJNZTv8/2cKfZduJX7SdDMU0F+YLn0FFLzM0y7BfyJjkx6ZV03SiJwJWTFIHOp/Oa8e5fHCYecPgAd02ydx9+isJm7k39haO03qs0yf1rfLvhGUK6eUycVO7S7g9QSR+XhoGU1bKkdO4eE0ZnmA0ko8kGr4EYmO6d2vq7biwPZQ/cfBVWh0SJ0Bp1v4TJ5C+FJufnqZUcsuihoFl0gEpImSKqV95Z+g+W9v16cJ3STcp/V9J0GV4sTV9ele/k6NX48KUVghnlChQLvPZLLIbC96s1J3jL+DcVZNONjAOFrTQZ9nSY4+5shfJjS5g9TqRDj8hs52sfIpfnpeOXEpGKnr1a2BOzOd0pFDbn5khr3J+QBxiQ+UWcs92QsVKlX6b02ESvidtAbpyfVypCRuL8Uu1tdxALdpG+CdinoK8dmfZTH1xkfE3hgqAc2DUsbzhObTiNjIFTzEYKFTg9x0HcQLsu3RJ7D/ewQ5BR/siYbuafyRzUXpfO/HicH42sbSrYJsbn6tkNZPsNNFhyocuz/4b+cui8yKiLDZdhJ7u/nsF3T8dxVl7RxaKk/6VHdp51rY+0
    AWS_ENDPOINTS: AgBri3TjrjcZRY8yo9RC1Qf5talVoICJYSaQlz9ahP3OAGeJPEK+JGOgfYFAAq8SVjQuj7eA7ee0C+M1iUuffrYMsuKN7UYAvKcuaA3UlewA4c/25HFrqCyuwy+Tp9ikT75iA54x5pqgOzVakahSAhWOQEGXK4uPIe2RL2Iul3PG7fGEGWWsj2Isx09xJHVsWDWobmCq+YbvhxF8NcWeDCQ8Upaz7GNVWblvF2ZGCKzIoi83Pz39zflgzm2B8q7LFbMFDzrOZi+HToshwBTHMmLcxY0ec/5uilae642kS+lt3BGTJAquxvjFzmyTKf3K+5u46KKMYHnar46uLShctGcFRb1o/lRRutdyCFnDU6BZz4gEuM7Igu/iq4F64l+oM0uOjdlW/7LZZz/1n1W0wP9g8ECh/wHThu0PsOTdbDEPDF3WH2qZx7wLI3sJF8nDk8gTjqSCWU7vZOFzneT8L79VHg6bDg5eg0G87fqo9yuP4rWvMukvZ8xb7DtkLGOmkdOxIKXFzB6SUUEXf7paW+6KPEznu/S6OOAGdI//ZDst7zuHpxuGdT4FzQpLq4m1WeXHK/bwcRSRP0ixnDC+jjURQD6o9dgZz+7dqodGYTv4k5vYAJAvnaWZsYd2Xrhb2BzzwC8kk9EkalxTXndErCyxaCgGkWrktqsUNxtTxrKdDKj3ZdekvPS4BrmUFl9uxtLmvHyPOtkhCSoPIgapVMzJ87TfUuLtGghtpYoYaQ0iUANbZDAbLUM=
    AWS_SECRET_ACCESS_KEY: AgCif7bI4NRGKHdT3PbdwTVjBQ1q0KAibta0LZztODJr3kaRseLYD71FzG9YuXcP4EbgaCxsmUf0c4/ESJjiUdrnNfc9gpIVigQ7d9W7rCNWSpKcW7578pC7DLKuq8zXMPkM26eRFgPcoppespS3IT/QYdacC3xqoadJdsZQF0rgFVrweNrCXZ9wAh48FlEBJVLsDeSnJn216f9M8ltOh3iYeqsABJ2wofvE3DVOxwS5TzInYDQNm2xaPBHMoORy6LYRPS8aNFPWIHx8TEieC7GIlfac1RyJehW7dPkyJQC4AzxFMM1q3StSJSFxZDfgMPRhXjwq4t5WIrbQkL3n29zfePz2xuz+mvGxh2wlU1a0U4xkSqHen1uXWZA5k/tzwUG5XWCb2yqItvN6yaANJV0E1e6NmJDQRw843K6DYL+hRVIFNoJPWtd0dT33dxbkburNtq+r3JJeqrYhdgFZG6DLXH8igxEj1nB9eZuzgGdxBX/CzsvOaeb3D/SKOoZg1jOujl0bT0NSpYG6p//y9rL1cWxnAAc12O0GkzfsYb9v4pqzvMTHgSTFAnA6/7mTCjQq2QwCRLAMHCPfXCmotFMApl6f+Wpd+TXlHGQsQX9Zk4HJaIRnyBtt/0PImsEBaCLvBDfGB1ZvABpwbc48/4NMrgeBmcJ2uTMC/xBOGTdBNeeMPvnYjaXenyYd3//oF9dSLljgYPO3gtAKc++VApB1wjbQseFUrQ1qI1de26x8
    VIRTUAL_HOSTED_STYLE: AgCLz6fUv2gWxsgBLxb50FVc2iuq93vz7ieRipH327WNDGIVKF3ZvgSX4egw0ProS4Aa8IPApDIjPMYbMaA/Fe4FGHBPKLWFYtvnxwxbFyDJ7O4EUPCupnlnEJFr29GfDq7FZ2f+tgpZDJz9N26GYLHssqyVnHMKRjyYVWGUcq96RmyEl2/JXP3sEoNuoMGZiFM58OXBmAQcUHbakgU9vXKnriRMEaJgzqWFxE37sBgwdRUWBTVy0772lC651hJ2JqcEq2CP2k8mVkMenVXs9pmsstxbLggJ12B5+ctSr856xE2JfhkpESlGkU0NgE99uz3csiK0XSApf/p90utInMo3WyqT1vtMpTTswkqhMnpP2ks79SospLuIO/JssqpKTwWpw7NwT3uvjVXJ7SZRdjphlw8luFjkfHgwgMmKQmMpB51+5YirrXxdl13hm0NKl1HHgooX/yodQEeE4riDxxP5tVQlTSPnXniKtkDFK54GqF7FD5tPgmJC5Ap0yQxDQieSn8fdLZyVGrEOeTYh+uLUV0FTPcRU9+UmdW85m69Sjj9VDZVvqWwPLbsw5sf1wu84oi/OSNG+9zG/+3tLl2am0NI2G8L/6Fpq4c7UXhyQy8YDVGxVeiEpq+zDf64+npvyQgznkpZxO8QTEktdibXn8G/Bv5EYiLnLSUFP8Way9AIoBRlfTjMeknvX/Utog+FWKPo6
  template:
    metadata:
      annotations:
        longhorn.io/backup-target: s3://nausicaea-longhorn@us-west-002/
      creationTimestamp: null
      name: longhorn-aws-secret
      namespace: longhorn-system
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.0
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 2
          defaultDataLocality: best-effort
          reclaimPolicy: Delete
          backupTargetName: default
        defaultSettings:
          defaultReplicaCount: 2
          defaultDataLocality: best-effort
        defaultBackupStore:
          backupTarget: "s3://nausicaea-longhorn@us-west-002/"
          backupTargetCredentialSecret: longhorn-aws-secret
          pollInterval: 300
        longhornUI:
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailscale
  namespace: longhorn-system
  annotations:
    tailscale.com/tags: "tag:longhorn,tag:k8s"
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - longhorn
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
