apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.0
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 2
          defaultDataLocality: best-effort
          reclaimPolicy: Delete
          backupTargetName: default
        defaultSettings:
          defaultReplicaCount: 2
          defaultDataLocality: best-effort
        defaultBackupStore:
          backupTarget: "s3://nausicaea-longhorn@us-west-002/"
          backupTargetCredentialSecret: longhorn-aws-secret
          pollInterval: 300
        longhornUI:
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
