apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.90.2
    # helm:
    #   valuesObject:
    #     admissionWebhooks:
    #       certManager: 
    #         enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opentelemetry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
