apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: victoria-logs-single
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.11.6
    helm:
      valuesObject:
        server:
          retentionPeriod: 7d
          persistentVolume:
            storageClassName: longhorn
        vector:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
