apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: appproj-nippon-koku
  source:
    chart: victoria-logs-single
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.11.6
    helm:
      parameters:
        - name: "server.service.clusterIP"
          value: null
      valuesObject:
        server:
          retentionPeriod: 7d
          persistentVolume:
            storageClassName: longhorn
          ingress:
            enabled: true
            annotations:
              tailscale.com/tags: "tag:victorialogs,tag:k8s"
            ingressClassName: tailscale
            hosts:
              - name: victorialogs
                path: ['/']
                port: http
            tls:
              - hosts:
                  - victorialogs
                  - victorialogs.takaya-map.ts.net
        vector:
          enabled: true
          image:
            base: debian
          extraVolumes:
            - name: run-log-journal
              hostPath:
                path: /run/log/journal
                type: Directory
          extraVolumeMounts:
            - name: run-log-journal
              mountPath: /run/log/journal
              readOnly: true
          customConfig:
            sources:
              journald_persistent:
                type: journald
                journal_directory: "/var/log/journal"
            transforms:
              journald_parser:
                type: remap
                inputs: [journald_persistent]
                source: |
                  .log = 
                      parse_json(.message) ?? 
                      parse_key_value(.message) ?? 
                      .message
                  if exists(.log.msg) {
                      .message = .log.msg
                  } else if exists(.log._msg) {
                      .message = .log._msg
                  } else if exists(.log.message) {
                      .message = .log.message
                  }
            sinks:
              vlogs:
                inputs: [parser,journald_parser]
                request:
                  headers:
                    VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace,_COMM,SYSLOG_IDENTIFIER,_TRANSPORT,host

  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
