apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetail-tailscale
  namespace: kubetail-system
  annotations:
    tailscale.com/tags: "tag:kubetail,tag:k8s"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kubetail-dashboard
      port:
        number: 8080
  tls:
    - hosts:
        - kubetail
        - kubetail.takaya-map.ts.net
