apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBSR/CwRRSoOc+f5MJnTPS9BTT9UuIIJlQK7qCP+YgMA6qZoDc7uMZQupTnGg5696AhZs13f7okqV0AV8Rz43DVdf7zIEatvXdZyONwTZDILe37D7lvkHMCQbo8tVISbLBZD11DcZ+njbUmXnt8gfBArGFS22B4RMyM0KGrQg7xrITNnOgc5PvMVFokzJM4t/61u3kRs1zsscD+jIlDMxUwdi57bN2tnl8SuM0j82X9v1aLNHVaeRtrNKNfeZO/0plVYlxuBqlTcV0PmPE6qjCNHXqqBWFDvi5+g/Xn3UpG/xHktnWBFYh9bE/RIN92I2RhkrVO53jrLsn0LASLpmmIZDQR1ttcoKJ7GR2H0omSQcqBC4MK5zEdRLpm3yEq+P1LwdSRtTOYaO2UDinAf414ChF8ZLUd79SPszeoLCEWkcdL/hq/xVanY8ceUmNsvcFBknKKH09o5dePXiODB3S1yWwYHFMF17jgP0+v4R4qsXLT+c7CvSay//EH35A8DIXrZzym2gElLMisFeN0yD186SZiHSodKB57HV126KKv1uQMYQQfAGhQQzJeKHwC5lZkLde2+hAfrJqrn0HI1aq/80v9gqjVWX8l1UOyhFGj2TZEvLzV+Qd/yUHg36rIH1pyvhjN6xf5WUBkgVM/31ma48dqhrrk2sxqLxkQXccrEsNUI8Pdp32y/XDhgLFg+CGlgmrIZemlu7TxYeCFr+hlQQ==
    client_secret: AgADC630qTAWIj8cumDrMJfa9ZzUsKoAwEYU5qkt21p4cBFi2VMHwGr1+kFYEcjWyTOXC0CWpAIbYyARacGKeiFlOTWw1+GLYqpECWKvgdEVlhDNwCYAiihk00QJfMvfNZ9iIJu8vwdWBVqviUkxM4wzQzgNFogAQQSOpqxlKJdKgf0haEK3QFN3paeq4NQ3cMAYBfeuRGAlnEqin5D5zHshg8TM4RjBixhzT/OqLHi3gSPw4UKj/+XwDmqQUeLbjTomnLBUehwTENMosjmlXhWm7+7Q+mD04slmKgInXBmfy9IL+nt4OG376Ef6/Uv4DKnpQ6KjTUMpsWoR26LxZPt9XazN1Y1LAMfUdOYvwAln5PrlHhTW5ehXvFRyL3f1cV7/otu2Ia+cv/C+zFUS8OD3Z/asVNNZUtAsN7wKAh5c5ys3TmIdr3glpjCt1sQEEoNh6u1RAewkHvDJMxoxD7CCuyHpNvBQYsMfL/3+EJjShMen8dKc4wU4/gVg4ujgJ0Jhzb1Nslfzm++E2BawXhhMn7tNl3CWSF7UqNglCP+iGeP7ysF9TAsHmksswYndTG8CkcEFC711HKq+ue4KPhcqlGhkgVLomrFOR0/0vO/qbbhbr71tQhWOXJzzDyi3obtRdozA+cHhQOJEELmIiBlrxwtDKdccCixrKz8CBZCn8J9BfkSCQKipu1eWvOigxsZpK0Xzgoz7OHRwT8NxUXcuUs2lykXnc61mvqE/kf2CxgWF/zQpnO4jl1kpCNV1oq1tQMnhuwX8ctLjk1w9xjwl
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
