apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-snowflake-proxy
  namespace: torproject
  labels:
    app.kubernetes.io/instance: snowflake-install
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: tor-snowflake-proxy
    app.kubernetes.io/version: v2.10.0
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: snowflake-install
      app.kubernetes.io/name: tor-snowflake-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: snowflake-install
        app.kubernetes.io/name: tor-snowflake-proxy
    spec:
      containers:
        - name: tor-snowflake-proxy
          image: containers.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake:v2.10.0
          imagePullPolicy: IfNotPresent
          args:
            - -metrics
            - -metrics-address
            - 0.0.0.0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: tor-snowflake-proxy
      serviceAccountName: tor-snowflake-proxy
      terminationGracePeriodSeconds: 30
