apiVersion: v1
kind: ServiceAccount
metadata:
  name: tor-snowflake-proxy
  namespace: torproject
  labels:
    app.kubernetes.io/instance: snowflake-install
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: tor-snowflake-proxy
    app.kubernetes.io/version: v2.10.0
