apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-tailscale
  namespace: argocd
  annotations:
    tailscale.com/tags: "tag:argocd,tag:k8s"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - argocd
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-argo-cd-server
                port:
                  number: 80
