apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailscale
  namespace: longhorn-system
  annotations:
    tailscale.com/tags: "tag:longhorn,tag:k8s"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: longhorn-frontend
      port:
        name: http
  tls:
    - hosts:
        - longhorn
        - longhorn.takaya-map.ts.net
