---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
data:
  eula.txt: |
    eula=true
  server.properties: |
    accepts-transfers=false
    allow-flight=false
    allow-nether=true
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    bug-report-link=https://github.com/nausicaea/minecraft/issues
    debug=false
    difficulty=easy
    enable-command-block=false
    enable-jmx-monitoring=false
    enable-query=true
    enable-rcon=false
    enable-status=true
    enforce-secure-profile=true
    enforce-whitelist=true
    entity-broadcast-range-percentage=100
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings={}
    hardcore=false
    hide-online-players=false
    initial-disabled-packs=
    initial-enabled-packs=vanilla
    level-name=world
    level-seed=-3866381874430228132
    level-type=minecraft\:normal
    log-ips=true
    max-chained-neighbor-updates=1000000
    max-players=10
    max-tick-time=60000
    max-world-size=29999984
    motd=Dive into other Worlds
    network-compression-threshold=256
    online-mode=true
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=true
    query.port=25566
    rate-limit=0
    rcon.password=
    rcon.port=
    region-file-compression=deflate
    require-resource-pack=false
    resource-pack=
    resource-pack-id=
    resource-pack-prompt=
    resource-pack-sha1=
    server-ip=0.0.0.0
    server-port=25565
    simulation-distance=10
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    sync-chunk-writes=true
    text-filtering-config=
    use-native-transport=true
    view-distance=10
    white-list=true
  opentelemetry.properties: |
    otel.service.name=minecraft
    otel.javaagent.debug=false
    otel.javaagent.logging=simple
    otel.exporter.otlp.protocol=grpc
    otel.exporter.otlp.endpoint=http://localhost:4317
    otel.traces.exporter=otlp
    otel.metrics.exporter=otlp
    otel.logs.exporter=otlp
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
        <Appenders>
            <Console name="console" target="SYSTEM_ERR">
                <PatternLayout pattern="[%level] [%logger{1}] [%class{1.}] %msg%n" />
            </Console>
            <OpenTelemetry name="OpenTelemetryAppender"/>
        </Appenders>
        <Loggers>
            <Root level="debug">
                <AppenderRef ref="console" level="info"/>
                <AppenderRef ref="OpenTelemetryAppender" level="all"/>
            </Root>
        </Loggers>
    </Configuration>
