---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-sidecar
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318

    processors:
      batch: {}

    exporters:
      debug: {}
      otlphttp:
        logs_endpoint: http://victorialogs-victoria-logs-single-server.victoriametrics.svc.cluster.local:9428/insert/opentelemetry/v1/logs

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlphttp]
