---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-sidecar
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 205

      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'IsMatch(body, "^ IN: ")'
            - 'IsMatch(body, "^OUT: ")'

      batch: {}

    exporters:
      debug: {}
      otlphttp:
        logs_endpoint: http://victorialogs-victoria-logs-single-server.victoriametrics.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        metrics_endpoint: http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428/insert/opentelemetry/v1/metrics

    service:
      telemetry:
        logs:
          level: info
      pipelines:
        logs:
          receivers: [otlp]
          processors: [filter, batch]
          exporters:
            - debug
            - otlphttp
