---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-sidecar
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
spec:
  mode: sidecar
  #image:
  #  repository: "otel/opentelemetry-collector-contrib"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 205

      resource/add_attrs:
        attributes:
          job: otelcol
          instance: minecraft

      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'IsMatch(body, "^ IN: ")'
            - 'IsMatch(body, "^OUT: ")'

      deltatocumulative:
        max_stale: 5m

      batch: {}

    exporters:
      debug: {}
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        metrics_endpoint: http://victoriametrics-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428/opentelemetry/v1/metrics
        logs_endpoint: http://victorialogs-victoria-logs-single-server.victoriametrics.svc.cluster.local:9428/insert/opentelemetry/v1/logs
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: info
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 9464
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [deltatocumulative, resource/add_attrs, batch]
          exporters: [otlphttp/victoriametrics]
        logs:
          receivers: [otlp]
          processors: [filter, batch]
          exporters: [otlphttp/victoriametrics]
