---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
spec:
  serviceName: minecraft-sts
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
  volumeClaimTemplates:
    - metadata:
        name: persistent
      spec:
        storageClassName: longhorn
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 20Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft
    spec:
      imagePullSecrets:
        - name: ghcr-nausicaea-minecraft
      volumes:
        - name: emptydir-config
          emptyDir: {}
        - name: emptydir-cache
          emptyDir: {}
        - name: emptydir-log
          emptyDir: {}
        - name: config
          projected:
            sources:
              - configMap:
                  name: server-config
                  items:
                    - key: server.properties
                      path: server/server.properties
                    - key: eula.txt
                      path: server/eula.txt
                    - key: opentelemetry.properties
                      path: server/opentelemetry.properties
                    - key: log4j2.xml
                      path: server/log4j2.xml
              - configMap:
                  name: player-config
                  items:
                    - key: banned-ips.json
                      path: player/banned-ips.json
                    - key: banned-players.json
                      path: player/banned-players.json
                    - key: ops.json
                      path: player/ops.json
                    - key: whitelist.json
                      path: player/whitelist.json
              - configMap:
                  name: mod-config
                  items:
                    - key: indigo-renderer.properties
                      path: mods/fabric/indigo-renderer.properties
                    - key: luckperms.conf
                      path: mods/luckperms/luckperms.conf
                    - key: auto-host.json
                      path: mods/polymer/auto-host.json
                    - key: client.json
                      path: mods/polymer/client.json
                    - key: common.json
                      path: mods/polymer/common.json
                    - key: resource-pack.json
                      path: mods/polymer/resource-pack.json
                    - key: server.json
                      path: mods/polymer/server.json
                    - key: AdvancedBackups-client.properties
                      path: mods/AdvancedBackups-client.properties
                    - key: AdvancedBackups.properties
                      path: mods/AdvancedBackups.properties
                    - key: ArcanaNovum.properties
                      path: mods/ArcanaNovum.properties
                    - key: c2me.toml
                      path: mods/c2me.toml
                    - key: cardinal-components-api.properties
                      path: mods/cardinal-components-api.properties
                    - key: dynamiclights.json
                      path: mods/dynamiclights.json
                    - key: ferritecore.mixin.properties
                      path: mods/ferritecore.mixin.properties
                    - key: forgeconfigapiport.toml
                      path: mods/forgeconfigapiport.toml
                    - key: getoffmylawn.json
                      path: mods/getoffmylawn.json
                    - key: leavesbegone-server.toml
                      path: mods/leavesbegone-server.toml
                    - key: letmedespawn.json
                      path: mods/letmedespawn.json
                    - key: lithostitched.json
                      path: mods/lithostitched.json
                    - key: midnightlib.json
                      path: mods/midnightlib.json
                    - key: pal.properties
                      path: mods/pal.properties
                    - key: polydex.json
                      path: mods/polydex.json
                    - key: polyfactory.json
                      path: mods/polyfactory.json
                    - key: sessility.properties
                      path: mods/sessility.properties
                    - key: stackdeobf.json
                      path: mods/stackdeobf.json
                    - key: tectonic.json
                      path: mods/tectonic.json
      initContainers:
        - name: init
          image: &minecraft_img ghcr.io/nausicaea/minecraft:v0.11.8-1.21.4
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -xe;
              cd /tmp/minecraft/etc;
              mkdir -vp default server player mods/luckperms/translations mods/messages;
              cp -vr /tmp/config-src/server/* server/;
              cp -vr /tmp/config-src/player/* player/;
              cp -vr /tmp/config-src/mods/* mods/;
              cp -vr /etc/minecraft/mods/luckperms/translations/* mods/luckperms/translations/;
              cp -vr /etc/minecraft/mods/messages/* mods/messages/;

              cd /tmp/minecraft/cache;
              mkdir -v .cache .fabric .polydex cache polymer stackdeobf_mappings;

              cd /tmp/minecraft/log;
              mkdir -v crash-reports;

              cd /tmp/minecraft/persistent;
              mkdir -vp backups luckperms universe/world/datapacks;
              cp -vr /var/lib/minecraft/persistent/universe/world/datapacks/*.zip universe/world/datapacks/;

              chown -vR 10001:10001 /tmp/minecraft;

          volumeMounts:
            - name: config
              mountPath: /tmp/config-src
              readOnly: true
            - name: persistent
              mountPath: /tmp/minecraft/persistent
            - name: emptydir-config
              mountPath: /tmp/minecraft/etc
            - name: emptydir-cache
              mountPath: /tmp/minecraft/cache
            - name: emptydir-log
              mountPath: /tmp/minecraft/log
      containers:
        - name: main
          image: *minecraft_img
          envFrom:
            - configMapRef:
                name: env-vars
          env:
            - name: JOLOKIA_BIND_ADDRESS
              value: 0.0.0.0:9422

          resources:
            requests:
              cpu: "6"
              memory: 4Gi
            limits:
              cpu: "6"
              memory: 4Gi

          volumeMounts:
            - name: persistent
              mountPath: /var/lib/minecraft/persistent
            - name: emptydir-config
              mountPath: /etc/minecraft
            - name: emptydir-cache
              mountPath: /var/cache/minecraft
            - name: emptydir-log
              mountPath: /var/log/minecraft
          ports:
            - name: minecraft
              containerPort: 30000
              protocol: TCP
            - name: discovery
              containerPort: 30000
              protocol: UDP
            - name: jolokia
              containerPort: 9422
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - /usr/local/bin/healthcheck
            periodSeconds: 5
            failureThreshold: 70
