---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft
  annotations:
    tailscale.com/hostname: "minecraft"
    tailscale.com/tags: tag:minecraft,tag:k8s,tag:public
spec:
  selector:
    app.kubernetes.io/name: minecraft
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
    - name: query
      port: 25566
      protocol: UDP
      targetPort: query
