---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      minecraft:
        port: 25565
        protocol: TCP
        exposedPort: 25565
        expose:
          default: true
      radicle:
        port: 8776
        protocol: TCP
        exposedPort: 8776
        expose:
          default: true
      
