---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ingressRoute:
      dashboard:
        enabled: true
    listeners:
      dns:
        port: 53
        protocol: TCP
      dnsudp:
        port: 53
        protocol: UDP
